### ISSUE TITLE
Add azurerm_storage_sync

### ISSUE THREAD

**Issue by schoenr79** [aztfmod/terraform-provider-azurecaf#102]
In order to follow the approach of CAF it is neccessary to add _azurerm_storage_sync_ to the provider

**Comment by schoenr79** [comment]
@arnaudlh i created a local branch of that change, but i am not able to push the branch to the origin on github.
I would be happy to be able to push it,to get a review on that.

regards
Roland

**Comment by arnaudlh** [comment]
hi @schoenr79 you will need to fork this repo in your git account, do the change and send the PR from there to here! 
looking forward to your contribution!

**Comment by arnaudlh** [comment]
Closing as PR merged. Thanks for your contribution @schoenr79
