### ISSUE TITLE
Add support for NetApp resources 

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/terraform-provider-azurecaf#119]
Add support for: 
- [ ] azurerm_netapp_account
- [ ] azurerm_netapp_pool
- [ ] azurerm_netapp_snapshot
- [ ] azurerm_netapp_volume

Could not find reference here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules. 

Based on portal discovery:

## azurerm_netapp_account:
- The name must be between 1 and 128 characters.
- The name cannot contain non-ASCII or special characters.
- Proposed slug: ana
- Proposed validation regex: "validation_regex": "\"^[a-zA-Z0-9][a-zA-Z0-9-_]{0,127}[a-zA-Z0-9]$\"",
- "regex": "\"[^0-9A-Za-z_-]\""

## azurerm_netapp_pool:
- The name cannot contain non-ASCII or special characters.
- The name must begin with a letter or a number and can contain letters, numbers, underscore ('_') and hyphens ('-') only.
- The name must be between 1 and 64 characters.
- Proposed slug: anp
- Proposed validation regex: "validation_regex": "\"^[a-zA-Z0-9][a-zA-Z0-9-_]{0,61}[a-zA-Z0-9]$\"",
- "regex": "\"[^0-9A-Za-z_-]\""

## azurerm_netapp_volume:
- The name must begin with a letter and can contain letters, numbers, underscore ('_') and hyphens ('-') only.
- The name must be between 1 and 64 characters.
- Proposed slug: anv
- Proposed validation regex: "validation_regex": "\"^[a-zA-Z0-9][a-zA-Z0-9-_]{0,61}[a-zA-Z0-9]$\"",
- "regex": "\"[^0-9A-Za-z_-]\""

## azurerm_netapp_snapshot:
- The name must begin with a letter or a number and can contain letters, numbers, underscore ('_') and hyphens ('-') only.
- The name must be between 1 and 255 characters.
- Proposed slug: anv
- Proposed validation regex: "validation_regex": "\"^[a-zA-Z0-9][a-zA-Z0-9-_]{0,61}[a-zA-Z0-9]$\"",
- "regex": "\"[^0-9A-Za-z_-]\""

**Comment by Nepomuceno** [comment]
Which ones can contain dashes (-)?
