### ISSUE TITLE
when random_length > zero, generated name does not comply with readme

### ISSUE THREAD

**Issue by gilles-o** [aztfmod/terraform-provider-azurecaf#127]
The readme says:
> **random_length** (optional) - default to `0` : configure additional characters to append to the generated resource name. 
> Random characters will remain compliant with the set of allowed characters per resources and will be appended **after** the suffixes

The random part is in fact inserted between name and suffixes, which is not the expected behavior.

```hcl
azurecaf_name "test" {}
  random_length = 5
  name = "some-name"
  suffixes = ["component", "env", "location"]
```
- produces : `"rg-some-name-rqxik-component-env-location"`
- Expected name (per readme): `"rg-some-name-component-env-location-rqxik"`

```hcl
azurecaf_name "test" {}
  random_length = 5
  name = ""
  suffixes = ["some-name", "component", "env", "location"]
```
- produces : `"rg-rqxik-some-name-component-env-location"`
- Expected name (per readme): `"rg-some-name-component-env-location-rqxik"`

Suggested fix:
change the components order (but will induce a breaking change)
or
change the doc

**Comment by arnaudlh** [comment]
good feeback @gilles-o, amended the doc!.
