### ISSUE TITLE
Add support for azurerm_monitor_*

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/terraform-provider-azurecaf#136]
Add support for azurerm_monitor_* resources, this is a dependency for https://github.com/aztfmod/terraform-azurerm-caf/pull/803

**Comment by robertdebock** [comment]
Just some input on what I found:

- There is no "Resource Type Code (short)" [recommended](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations). I suggest `mvmss`
- I can't find the minimum, nor maximum allowed length for the name. I suggest `minimum: 2`, `maximum: 64`.
- Based on [examples](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_autoscale_setting#example-usage) I think both upper and lower case are allowed; `lower: false`.
- The regular expression (though difficult to determine): `"^[a-zA-Z0-9][a-zA-Z0-9-]{0,62}[a-zA-Z0-9]$"` (An alphanumeric character, followed by an alphanumeric character or a dash, repeat that 0 to 62 times, followed by an alphanumeric character. That should combine into a maximum length of 64 characters.)

That would result into this line to add to [the table](https://github.com/aztfmod/terraform-provider-azurecaf/blob/master/docs/resources/azurecaf_name.md)

| Resource type           | Resource type code (short)  | minimum length  |  maximum length | lowercase only | validation regex                          |
| ------------------------| ----------------------------|-----------------|-----------------|----------------|-------------------------------------------|
| azurerm_monitor_autoscale_setting| mvmss| 2| 64| false|"^[a-zA-Z0-9][a-zA-Z0-9-]{0,62}[a-zA-Z0-9]$"|
