### ISSUE TITLE
Problems in the datasource/resource evaluation order

### ISSUE THREAD

**Issue by etiennejournet** [aztfmod/terraform-provider-azurecaf#159]
Hello team ! 

Thanks for your work on this module :) 
I wanted to signal that I had some problems with resource creation order (which made me wonder why you didn't make this a datasource ?)

In short the problem comes from datasources being evaluated first at plan, and If you need to use a datasource that depends on a `azurecaf ` resource it can make your terraform plan unable to resolve this datasource (and to access subsequent resources).

Here is an example : 
- Declare a datasource
```
data "azurerm_kubernetes_cluster" "main" {
  name                = "my-cluster-name"
  resource_group_name = "rg-name-azurecaf-style"
}
```
- Use this datasource in a provider 
```
provider "kubernetes" {
  host                   = data.azurerm_kubernetes_cluster.main.kube_admin_config.0.host
  username               = data.azurerm_kubernetes_cluster.main.kube_admin_config.0.username
  password               = data.azurerm_kubernetes_cluster.main.kube_admin_config.0.password
  client_certificate     = base64decode(data.azurerm_kubernetes_cluster.main.kube_admin_config.0.client_certificate)
  client_key             = base64decode(data.azurerm_kubernetes_cluster.main.kube_admin_config.0.client_key)
  cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.main.kube_admin_config.0.cluster_ca_certificate)
}
```
- Now you want to refactor and introduce the azurecaf provider
```
## Lets assume this will result in "rg-name-azurecaf-style" (it's basically identical to the hardcoded name above)
resource "azurecaf_name" "rg" {
  resource_type = "azurerm_resource_group"
  name          = local.naming_convention_name
  suffixes      = local.naming_convention_suffixes_list
} 
```
- Use it in your datasource
```
data "azurerm_kubernetes_cluster" "main" {
  name                = "my-cluster-name"
  resource_group_name = azurecaf_name.rg.result["azurerm_resource_group"]
}
```
Now, your  `kubernetes` provider is unable to read its resources at plan time, because it depends on a `azurecaf ` resource that isn't created.

**Comment by Nepomuceno** [comment]
It makes completly sense sorry I never thought about this before with the upcoming new version 2.0.0 I will add it as data this way you could have it as data instead of resource if you want to to avoid this kind of thing.

**Comment by arnaudlh** [comment]
Closing as introduced in https://github.com/aztfmod/terraform-provider-azurecaf/releases/tag/v1.2.22.
We will roll out in the next major version of the caf module
Feel free to reopen if not solved.
