### ISSUE TITLE
azurerm_user_assigned_identity missing from doc

### ISSUE THREAD

**Issue by sebastus** [aztfmod/terraform-provider-azurecaf#171]
azurerm_user_assigned_identity appears in the readme.md, but not in https://github.com/aztfmod/terraform-provider-azurecaf/blob/main/docs/resources/azurecaf_name.md. What's the slug?

**Comment by arnaudlh** [comment]
Truth is in the code ;) 

https://github.com/aztfmod/terraform-provider-azurecaf/blob/1c4e3fb6b7cbcf23ece99dbb662755cd3b3dcda9/resourceDefinition.json#L2636
