### ISSUE TITLE
1.2.18 is not published on registry

### ISSUE THREAD

**Issue by Poil** [aztfmod/terraform-provider-azurecaf#175]
Hi

1.2.18 is not published on registry

**Comment by arnaudlh** [comment]
on this week's todo list :)

**Comment by Shr3ps** [comment]
👀

**Comment by Shr3ps** [comment]
Fixed with https://github.com/aztfmod/terraform-provider-azurecaf/releases/tag/v1.2.18 release

**Comment by arnaudlh** [comment]
Closing as published :)
