### ISSUE TITLE
A provider named "azurecaf" could not be found in the Terraform Registry

### ISSUE THREAD

**Issue by irom77** [aztfmod/terraform-provider-azurecaf#19]
Getting these below when trying to plan the landing zone
`[[vscode@c67f676d4b35 caf]$ rover /tf/caf/landingzones/landingzone_caf_foundations plan](url)`

See the error

```
...
Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "random" (hashicorp/random) 2.2.1...
- Downloading plugin for provider "azurerm" (hashicorp/azurerm) 2.2.0...

Provider "azurecaf" not available for installation.

A provider named "azurecaf" could not be found in the Terraform Registry.
....
Error: no provider exists with the given name
```

**Comment by arnaudlh** [comment]
hi @irom77 the azurecaf provider should be included in the rover already, can you please confirm which version you are using? When you go to the .devcontainer folder, please make sure you have the latest (```image: aztfmod/rover:2005.1510```) inside your ```docker-compose.yml```
