### ISSUE TITLE
Improve azurerm_windows_virtual_machine Resource Name Length up to 64 characters

### ISSUE THREAD

**Issue by schoenr79** [aztfmod/terraform-provider-azurecaf#199]
Since Azure Resource Manager (ARM) was introduced, the possible length of a windows vm resource name is up to 64 characters.

At the moment this is not possible because the naming provider does it restrict to max. of 15 characters.

Either if we use the "passthrough" or "clean_input" option it is not possible to go up to the max of 64 characters. 

In the naming provider this should be increased to the maximum of 64 characters, in order to have the maximum available. 

While the [_azurerm_windows_virtual_machine_  name resource is used for the host-/computername](https://github.com/aztfmod/terraform-azurerm-caf/blob/main/modules/compute/virtual_machine/vm_windows.tf#L15) too, the max. length of 15 characters for this property should be restricted directly in referencing modules itself.  It may be achievable with the [substr()](https://www.terraform.io/language/functions/substr) function of terraform

**Comment by arnaudlh** [comment]
Closing as merged and released in 1.2.21
