### ISSUE TITLE
Add support to apply policies at subscription and resource group level.

### ISSUE THREAD

**Issue by m-rajagopal** [aztfmod/terraform-provider-azurecaf#204]
Add support to 

--azurerm_subscription_policy_assignment
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription_policy_assignment

--azurerm_subscription_policy_exemption
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription_policy_exemption

--azurerm_resource_group_policy_assignment
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_group_policy_assignment

--azurerm_resource_group_policy_exemption
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_group_policy_exemption

**Comment by arnaudlh** [comment]
Closing as merged and ramp for 1.2.22
