### ISSUE TITLE
Add support for Log Analytics Dedicated Cluster

### ISSUE THREAD

**Issue by BlauerPulli** [aztfmod/terraform-provider-azurecaf#232]
Recently started to work with log analytics clusters and realized, that azurecaf not support this resource yet.

https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/azure-monitor/logs/logs-dedicated-clusters.md

**Comment by LaurentLesle** [comment]
@BlauerPulli are you going to submit a PR?
