### ISSUE TITLE
Add support for azurerm_monitor_private_link_scoped_service

### ISSUE THREAD

**Issue by LaurentLesle** [aztfmod/terraform-provider-azurecaf#240]
azurerm_monitor_private_link_scope
azurerm_monitor_private_link_scoped_service

**Comment by LaurentLesle** [comment]
https://github.com/aztfmod/terraform-azurerm-caf/pull/1425

**Comment by arnaudlh** [comment]
```azurerm_monitor_private_link_scope``` is already implemented .
Regarding ```azurerm_monitor_private_link_scope_service``` I suggest we follow the portal's logic which is to reuse service name, hence not needing to implement ```azurerm_monitor_private_link_scope_service```.
I will close, feel free to re-open if the assessment changes.
