### ISSUE TITLE
Event hub fails when prefix is only numerical values

### ISSUE THREAD

**Issue by LaurentLesle** [aztfmod/terraform-provider-azurecaf#26]
https://github.com/Azure/caf-terraform-landingzones/runs/817483036?check_suite_focus=true

![image](https://user-images.githubusercontent.com/4702224/85981804-60d7f000-ba17-11ea-98e3-302c331e62ff.png)

**Comment by nyuen** [comment]
The evenhub does not allow starting with a number - we should review the prefix strategy to enforce a defined set of characters
