### ISSUE TITLE
Naming convention method for a new module- Azure cognitive search service

### ISSUE THREAD

**Issue by leelasatyavathip** [aztfmod/terraform-provider-azurecaf#267]
Need support for automatic caf naming convention method to a new module that will be developed - azure cognitive search service

**Comment by arnaudlh** [comment]
![image](https://github.com/aztfmod/terraform-provider-azurecaf/assets/20535201/69b20405-faa4-4fe6-848d-6c20a6783e51)

**Comment by leelasatyavathip** [comment]
[https://github.com/aztfmod/terraform-provider-azurecaf/pull/269](url)

**Comment by arnaudlh** [comment]
Closing as merged
