### ISSUE TITLE
Add support for azurerm_data_protection_backup_policy_postgresql_flexible_server

### ISSUE THREAD

**Issue by sschne** [aztfmod/terraform-provider-azurecaf#292]
Add support for azurerm_data_protection_backup_policy_postgresql_flexible_server

Although i'm not sure why the resource needs it's own resource type, other backup vault policies all have it's own resource type, so requesting to add it here. If it's not needed i can also add the resource in the terraform-azurerm-caf module without an azurecaf_name

**Comment by arnaudlh** [comment]
Closing as #293 merged.
