### ISSUE TITLE
Add support for Azure Private DNS zones and its virtual network links

### ISSUE THREAD

**Issue by iriahk89** [aztfmod/terraform-provider-azurecaf#34]
![image](https://user-images.githubusercontent.com/19380966/92555281-e094fd00-f299-11ea-8fe9-ad2ef3e09c7c.png)

**Comment by nyuen** [comment]
Hi @iriahk89, we had a look at the issue and considering that the expected domain name (i.e contoso.com) it doesn't make sense to temper with the name. For instance we don't want to generate privatezone-contoso.com as a result of using the naming convention
