### ISSUE TITLE
azurerm_synapse_workspace name can contain only lowercase letters or numbers, and be between 1 and 45 characters long

### ISSUE THREAD

**Issue by LaurentLesle** [aztfmod/terraform-provider-azurecaf#39]
![image](https://user-images.githubusercontent.com/4702224/93298203-63cbcb00-f825-11ea-9f04-6b4d7b2b0e92.png)

![image](https://user-images.githubusercontent.com/4702224/93298165-51ea2800-f825-11ea-8b98-272e425a3f68.png)

**Comment by nyuen** [comment]
We need to implement azurerm_synapse_* resources, before we do that do you have additional resource type that needs to be implemented?

The azurerm_machine_learning_workspace resource is ok and inline with the Azure docs

**Comment by LaurentLesle** [comment]
This is the only one having an issue
