### ISSUE TITLE
Bug: Naming convention for azurerm_synapse_workspace accepts lowercase letters & numbers only

### ISSUE THREAD

**Issue by singh-rahul** [aztfmod/terraform-provider-azurecaf#46]
1. **azurerm_synapse_workspace** : Naming convention accepts lowercase letters & numbers only.
Max Length : 45 char.
Screenshot attached for reference : 
![synapse_naming](https://user-images.githubusercontent.com/39583459/94260735-46080f80-ff63-11ea-9f91-be6e32f5b8ea.PNG)

2. **azurerm_synapse_spark_pool**  : Create naming convention with below rules
[name can contain only letters or numbers, must start with a letter, and be between 1 and 15 characters long]

3. **azurerm_synapse_sql_pool** : Create naming convention with below rules
[name can contain only letters or numbers, must start with a letter, and be between 1 and 15 characters long]

**Comment by Nepomuceno** [comment]
This is in master already https://github.com/aztfmod/terraform-provider-azurecaf/blob/9f88d3e47e804e81a79ea70f12c9613b4a8295ce/resourceDefinition.json#L2157-L2167

**Comment by singh-rahul** [comment]
@Nepomuceno : There is extra space before closing quote - "name": "azurerm_synapse_sql_pool  "  . Kindly remove this.
Thanks
