### ISSUE TITLE
Add support for azurerm_monitor_diagnostic_setting

### ISSUE THREAD

**Issue by sebastus** [aztfmod/terraform-provider-azurecaf#62]
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting

This is especially important now because it's possible to add a diagnostic setting to a resource, then that resource can get deleted without the diagnostic setting. Need to be able to generate random names for the diagnostic settings as a workaround until the azure monitor team fixes it.

**Comment by sebastus** [comment]
added the resource in pr #63

**Comment by arnaudlh** [comment]
Closing as merged in #pr63
