### ISSUE TITLE
Invalid name for CAF naming azurerm_key_vault vmsecrets, the pattern ^[a-zA-Z][a-zA-Z0-9-]{1,22}[a-zA-Z0-9]$ doesn't match 5-kv-vmsecrets

### ISSUE THREAD

**Issue by LaurentLesle** [aztfmod/terraform-provider-azurecaf#73]
Error when setting the prefix value to "5"

**Comment by nyuen** [comment]
Can you attach the code to reproduce?

**Comment by nyuen** [comment]
Keyvault cannot start with a numeric value and doesn't accept 5 as a prefix

Vault name must only contain alphanumeric characters and dashes and cannot start with a number.
Vault name must be between 3-24 alphanumeric characters. The name must begin with a letter, end with a letter or digit, and not contain consecutive hyphens

**Comment by nyuen** [comment]
Re-opening for discussion. 

The prefix is not valid and the error message is expected. Two option : 
1. leave the error message as this is expected
2. prevent prefix starting with a number

Open to discussion @LaurentLesle, @Nepomuceno,

**Comment by arnaudlh** [comment]
Closing as expired.
