### ISSUE TITLE
APIM name

### ISSUE THREAD

**Issue by hieumoscow** [aztfmod/terraform-provider-azurecaf#74]
I have this error for var.name = "apim"

Error: Invalid name for CAF naming azurerm_api_management_service apim, the pattern ^[a-z][a-zA-Z0-9-][a-zA-Z0-9]{0,48}$ doesn't match vsic-apim-apim

Please help to review

**Comment by nyuen** [comment]
Can provide the exemple?

**Comment by nyuen** [comment]
Fixed in 1.1.9
