### ISSUE TITLE
Implement naming support for azurerm_virtual_desktop_* types

### ISSUE THREAD

**Issue by jleonelion** [aztfmod/terraform-provider-azurecaf#76]
Please add naming convention support for the following resource types:
azurerm_virtual_desktop_application_group | ❌
azurerm_virtual_desktop_host_pool | ❌
azurerm_virtual_desktop_workspace | ❌

If you want me to implement this personally, please assign to me and I'll submit PR

**Comment by Nepomuceno** [comment]
Corrected in #77
