### ISSUE TITLE
Azure Machine Learning Compute Instance name

### ISSUE THREAD

**Issue by arnaudlh** [aztfmod/terraform-provider-azurecaf#78]
When deploying Azure Machine Learning Workspace, the compute instance name is currently not supported, 

We need to create resource type to match the required value: "Compute name is invalid. It can include letters, digits and dashes. It must start with a letter, end with a letter or digit, and be between 3 and 24 characters in length"

CC @benhurjoel @singh-rahul for more details if needed.

**Comment by Nepomuceno** [comment]
You can use the VM that has this restriction. According to the docs the supported value for Machine Learning workspaces it is correct https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftmachinelearning
