### ISSUE TITLE
validationRegex is wrong for azurerm_servicebus_namespace

### ISSUE THREAD

**Issue by jason-swissre** [aztfmod/terraform-provider-azurecaf#86]
The regex allows the slug "sb" to be added at the end of the name but this is not valid.  No azurerm_servicebus_namespace may be created with a name which ends in "-", "sb" or "mgmt".

**Comment by Nepomuceno** [comment]
The slug should not go in the end of the name but I get if you have no name and no random chars it will create with sb in the name. The best way to solve this would be to change the slug of the namespace but this would be a breaking change for people that have it already provisioned.

I will try to think about a good solution if you have any suggestion

**Comment by arnaudlh** [comment]
closing as not active.
