### ISSUE TITLE
Activity Log Alert Naming

### ISSUE THREAD

**Issue by benhurjoel** [aztfmod/terraform-provider-azurecaf#92]
Please include support for Activity Log Alerts :

Length : 1-260
Valid Characters : 
Can't use  <>*%{}&:\\?+/# 
Can't end with space or period.

Ref : 
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_activity_log_alert

**Comment by arnaudlh** [comment]
Closing as implemented in #92
