### ISSUE TITLE
Add support for hyphens in OS disk name

### ISSUE THREAD

**Issue by chris-p-martin** [aztfmod/terraform-provider-azurecaf#94]
Hello,

The Microsoft documentation for the managed disk naming convention was updated recently to include the fact hyphens can be used in the name. Link to the updated documenation is [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftcompute)

I've raised a PR #91  to add support for this in the module. The build is failing but I don't believe this related to my changes. Is it possible for someone to review and approve the PR.

Thanks,
Chris

**Comment by arnaudlh** [comment]
Closing this one as merged by Gabriel and included in v1.2.3
